
# Exercise 1 — Model Design (10 min)

## Scenario

Your task system needs a `comments` table.

Each comment belongs to:
- one task
- one user

---

## Task

Create a new Colab cell and write the `Comment` model.

### Required Fields

- `id`
- `task_id`
- `user_id`
- `content`
- `created_at`

class Comment(Base):
    __tablename__ = "comments"
    id           = Column(Integer, primary_key=True)
    task_id      = Column(Integer, ForeignKey("tasks.id"))
    user_id      = Column(Integer, ForeignKey("users.id"))
    content      = Column(String(1000), nullable=False)
    created_at   = Column(DateTime, server_default=func.current_timestamp())
    
comments = relationship(
    "Comment",
    back_populates="task",
    cascade="all, delete"
)

comments = relationship(
    "Comment",
    back_populates="user"
)

## Questions

1. What relationships should `Comment` have?
    task = relationship("Task", back_populates="comments")
    user = relationship("User", back_populates="comments")
2. Should `Task` have a `comments` relationship?
    -- yes, allows easy acces to task.comments
3. What should happen to comments when a task is deleted?
    -- on cascade delete al comments

# Exercise 2 — Migration Creation (10 min)

## Scenario

You added the `Comment` model.

Now generate a migration programmatically.

---

## Task

Run:

```python
command.revision(
    alembic_cfg,
    autogenerate=True,
    message="add comments table"
)
```
Generating /content/alembic/versions/07822985ed31_initial_schema.py ...  done
Generated migrations:
  /content/alembic/versions/07822985ed31_initial_schema.py

## Then Inspect the Migration

```python
import glob

migration_files = sorted(
    glob.glob('/content/project/alembic/versions/*.py')
)

for f in migration_files:
    print(f)
```
"""Initial schema

Revision ID: 07822985ed31
Revises: 
Create Date: 2026-05-14 14:31:27.055745
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07822985ed31'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###

## Open the Generated Migration

```python
latest = migration_files[-1]

with open(latest) as f:
    print(f.read())
```


## Questions

1. What does `upgrade()` do?
    --moves database schema to  new version
2. What does `downgrade()` do?
    -- moves database vertion to previous one
3. What happens if you downgrade this migration?
    -- comments table will be deleted
# Exercise 4 — Migration Rollback (5 min)

## Scenario

You added a bad column:
`estimated_hours`

The migration has already been applied.

---

## Task

Rollback the migration programmatically.

### Example

```python
command.downgrade(alembic_cfg, "-1")
```

---

## Questions

1. What happens to the column?
    -- it is deleted
2. What happens to the data?
    -- it is lost

---

# Exercise 5 — Concept Check (5 min)

Answer briefly:

1. Why use ORM instead of raw SQL?
    -- improves readability, reduces errors, and makes database migration e=simpler
2. Why use migrations?
    -- makes version controll easier
3. When would you rollback?
    -- when a transaction fails or produces an error
4. Difference between `add()` and `commit()`?
    -- marks the objest as to be inserted or created in the database
    -- actaully commits to the database the objects add()ed 
5. Why are relationships useful?
    -- allows us to link tables to better visualize the table's data